// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct GameMetadataData {
  int16 vaultChestCoordX;
  int16 vaultChestCoordY;
  int16 vaultChestCoordZ;
}

library GameMetadata {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "vaultguard", name: "GameMetadata", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627661756c7467756172640000000047616d654d6574616461746100000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0006030002020200000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (int16, int16, int16)
  Schema constant _valueSchema = Schema.wrap(0x0006030021212100000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "vaultChestCoordX";
    fieldNames[1] = "vaultChestCoordY";
    fieldNames[2] = "vaultChestCoordZ";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get vaultChestCoordX.
   */
  function getVaultChestCoordX() internal view returns (int16 vaultChestCoordX) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int16(uint16(bytes2(_blob))));
  }

  /**
   * @notice Get vaultChestCoordX.
   */
  function _getVaultChestCoordX() internal view returns (int16 vaultChestCoordX) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int16(uint16(bytes2(_blob))));
  }

  /**
   * @notice Set vaultChestCoordX.
   */
  function setVaultChestCoordX(int16 vaultChestCoordX) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((vaultChestCoordX)), _fieldLayout);
  }

  /**
   * @notice Set vaultChestCoordX.
   */
  function _setVaultChestCoordX(int16 vaultChestCoordX) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((vaultChestCoordX)), _fieldLayout);
  }

  /**
   * @notice Get vaultChestCoordY.
   */
  function getVaultChestCoordY() internal view returns (int16 vaultChestCoordY) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int16(uint16(bytes2(_blob))));
  }

  /**
   * @notice Get vaultChestCoordY.
   */
  function _getVaultChestCoordY() internal view returns (int16 vaultChestCoordY) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int16(uint16(bytes2(_blob))));
  }

  /**
   * @notice Set vaultChestCoordY.
   */
  function setVaultChestCoordY(int16 vaultChestCoordY) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((vaultChestCoordY)), _fieldLayout);
  }

  /**
   * @notice Set vaultChestCoordY.
   */
  function _setVaultChestCoordY(int16 vaultChestCoordY) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((vaultChestCoordY)), _fieldLayout);
  }

  /**
   * @notice Get vaultChestCoordZ.
   */
  function getVaultChestCoordZ() internal view returns (int16 vaultChestCoordZ) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int16(uint16(bytes2(_blob))));
  }

  /**
   * @notice Get vaultChestCoordZ.
   */
  function _getVaultChestCoordZ() internal view returns (int16 vaultChestCoordZ) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (int16(uint16(bytes2(_blob))));
  }

  /**
   * @notice Set vaultChestCoordZ.
   */
  function setVaultChestCoordZ(int16 vaultChestCoordZ) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((vaultChestCoordZ)), _fieldLayout);
  }

  /**
   * @notice Set vaultChestCoordZ.
   */
  function _setVaultChestCoordZ(int16 vaultChestCoordZ) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((vaultChestCoordZ)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (GameMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (GameMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(int16 vaultChestCoordX, int16 vaultChestCoordY, int16 vaultChestCoordZ) internal {
    bytes memory _staticData = encodeStatic(vaultChestCoordX, vaultChestCoordY, vaultChestCoordZ);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(int16 vaultChestCoordX, int16 vaultChestCoordY, int16 vaultChestCoordZ) internal {
    bytes memory _staticData = encodeStatic(vaultChestCoordX, vaultChestCoordY, vaultChestCoordZ);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(GameMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.vaultChestCoordX, _table.vaultChestCoordY, _table.vaultChestCoordZ);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(GameMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.vaultChestCoordX, _table.vaultChestCoordY, _table.vaultChestCoordZ);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (int16 vaultChestCoordX, int16 vaultChestCoordY, int16 vaultChestCoordZ) {
    vaultChestCoordX = (int16(uint16(Bytes.getBytes2(_blob, 0))));

    vaultChestCoordY = (int16(uint16(Bytes.getBytes2(_blob, 2))));

    vaultChestCoordZ = (int16(uint16(Bytes.getBytes2(_blob, 4))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (GameMetadataData memory _table) {
    (_table.vaultChestCoordX, _table.vaultChestCoordY, _table.vaultChestCoordZ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    int16 vaultChestCoordX,
    int16 vaultChestCoordY,
    int16 vaultChestCoordZ
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(vaultChestCoordX, vaultChestCoordY, vaultChestCoordZ);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    int16 vaultChestCoordX,
    int16 vaultChestCoordY,
    int16 vaultChestCoordZ
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(vaultChestCoordX, vaultChestCoordY, vaultChestCoordZ);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
