// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ShopMetadataData {
  bytes32 chestEntityId;
  address paymentToken;
  address shopNFT;
  uint256 shopNFTNextTokenId;
}

library ShopMetadata {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "parkourchest", name: "ShopMetadata", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74627061726b6f75726368657374000053686f704d6574616461746100000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0068040020141420000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, address, address, uint256)
  Schema constant _valueSchema = Schema.wrap(0x006804005f61611f000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "chestEntityId";
    fieldNames[1] = "paymentToken";
    fieldNames[2] = "shopNFT";
    fieldNames[3] = "shopNFTNextTokenId";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get chestEntityId.
   */
  function getChestEntityId() internal view returns (bytes32 chestEntityId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get chestEntityId.
   */
  function _getChestEntityId() internal view returns (bytes32 chestEntityId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set chestEntityId.
   */
  function setChestEntityId(bytes32 chestEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((chestEntityId)), _fieldLayout);
  }

  /**
   * @notice Set chestEntityId.
   */
  function _setChestEntityId(bytes32 chestEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((chestEntityId)), _fieldLayout);
  }

  /**
   * @notice Get paymentToken.
   */
  function getPaymentToken() internal view returns (address paymentToken) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get paymentToken.
   */
  function _getPaymentToken() internal view returns (address paymentToken) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set paymentToken.
   */
  function setPaymentToken(address paymentToken) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((paymentToken)), _fieldLayout);
  }

  /**
   * @notice Set paymentToken.
   */
  function _setPaymentToken(address paymentToken) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((paymentToken)), _fieldLayout);
  }

  /**
   * @notice Get shopNFT.
   */
  function getShopNFT() internal view returns (address shopNFT) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get shopNFT.
   */
  function _getShopNFT() internal view returns (address shopNFT) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set shopNFT.
   */
  function setShopNFT(address shopNFT) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((shopNFT)), _fieldLayout);
  }

  /**
   * @notice Set shopNFT.
   */
  function _setShopNFT(address shopNFT) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((shopNFT)), _fieldLayout);
  }

  /**
   * @notice Get shopNFTNextTokenId.
   */
  function getShopNFTNextTokenId() internal view returns (uint256 shopNFTNextTokenId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get shopNFTNextTokenId.
   */
  function _getShopNFTNextTokenId() internal view returns (uint256 shopNFTNextTokenId) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set shopNFTNextTokenId.
   */
  function setShopNFTNextTokenId(uint256 shopNFTNextTokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((shopNFTNextTokenId)), _fieldLayout);
  }

  /**
   * @notice Set shopNFTNextTokenId.
   */
  function _setShopNFTNextTokenId(uint256 shopNFTNextTokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((shopNFTNextTokenId)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (ShopMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (ShopMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 chestEntityId, address paymentToken, address shopNFT, uint256 shopNFTNextTokenId) internal {
    bytes memory _staticData = encodeStatic(chestEntityId, paymentToken, shopNFT, shopNFTNextTokenId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 chestEntityId, address paymentToken, address shopNFT, uint256 shopNFTNextTokenId) internal {
    bytes memory _staticData = encodeStatic(chestEntityId, paymentToken, shopNFT, shopNFTNextTokenId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(ShopMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.chestEntityId,
      _table.paymentToken,
      _table.shopNFT,
      _table.shopNFTNextTokenId
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(ShopMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.chestEntityId,
      _table.paymentToken,
      _table.shopNFT,
      _table.shopNFTNextTokenId
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (bytes32 chestEntityId, address paymentToken, address shopNFT, uint256 shopNFTNextTokenId) {
    chestEntityId = (Bytes.getBytes32(_blob, 0));

    paymentToken = (address(Bytes.getBytes20(_blob, 32)));

    shopNFT = (address(Bytes.getBytes20(_blob, 52)));

    shopNFTNextTokenId = (uint256(Bytes.getBytes32(_blob, 72)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ShopMetadataData memory _table) {
    (_table.chestEntityId, _table.paymentToken, _table.shopNFT, _table.shopNFTNextTokenId) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    bytes32 chestEntityId,
    address paymentToken,
    address shopNFT,
    uint256 shopNFTNextTokenId
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(chestEntityId, paymentToken, shopNFT, shopNFTNextTokenId);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 chestEntityId,
    address paymentToken,
    address shopNFT,
    uint256 shopNFTNextTokenId
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(chestEntityId, paymentToken, shopNFT, shopNFTNextTokenId);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
