// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TotalSupply } from "./tables/TotalSupply.sol";
import { ObjectToken } from "./tables/ObjectToken.sol";
import { Metadata } from "./tables/Metadata.sol";
