// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Metadata } from "./tables/Metadata.sol";
import { ShopNFT } from "./tables/ShopNFT.sol";
import { OwnedNFTs } from "./tables/OwnedNFTs.sol";
import { NFTMetadata, NFTMetadataData } from "./tables/NFTMetadata.sol";
import { MintedNFT } from "./tables/MintedNFT.sol";
