// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PlayerMetadata } from "./tables/PlayerMetadata.sol";
import { BuildIds } from "./tables/BuildIds.sol";
import { BuildMetadata, BuildMetadataData } from "./tables/BuildMetadata.sol";
import { Builder } from "./tables/Builder.sol";
import { Metadata } from "./tables/Metadata.sol";
