// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IChipSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IChipSystem {
  function parkourchest__changeAdmin(bytes32 entityId, address newAdmin) external;

  function parkourchest__setDisplayData(bytes32 entityId, string memory name, string memory description) external;

  function parkourchest__claimNft() external;
}
