// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IChipSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IChipSystem {
  function overflowchest__changeAdmin(bytes32 entityId, address newAdmin) external;

  function overflowchest__setDisplayData(bytes32 entityId, string memory name, string memory description) external;

  function overflowchest__configurePipeAccess(
    bytes32 chestEntityId,
    bytes32 callerEntityId,
    bool depositAllowed,
    bool withdrawAllowed
  ) external;

  function overflowchest__configurePipeAccess(
    bytes32 chestEntityId,
    bytes32[] memory addCallerEntityIds,
    bytes32[] memory removeCallerEntityIds
  ) external;
}
